### ISSUE TITLE
how to insert html instead of media

### ISSUE THREAD

**Issue by capsule5** [kbdaitch/angular-slick-carousel#14]
To do something like that:

`<slick settings="slickConfig" control="slickHandle" >
	<div ng-repeat="slide in slides"></div>
</slick>`

**Comment by kbdaitch** [comment]
Use the `src` attribute, and use a separate template for:
```html
<div ng-repeat="slide in slides" on-finish-render="init()">
</div>
```

The `on-finish-render` uses a directive defined `init` function to ensure running slickification when `ng-repeat` is done rendering.

**Comment by capsule5** [comment]
Thanks for the quick answer

**Comment by capsule5** [comment]
I might have miss something on your explanation. Try on your example to remove the media="media" and nothing work anymore. Every content inside the <slick> is removed. Also what should be in the init() function called by on-finish-render="init()"?

**Comment by kbdaitch** [comment]
Either you could use [angular-slick](https://www.google.com/url?sa=t&source=web&rct=j&ei=TeNMVYqlH5KxyATHjoC4Bg&url=https://github.com/vasyabigi/angular-slick&ved=0CBwQFjAA&usg=AFQjCNFY1nthc8x0vX0zYs1tGX1DE9RcFA&sig2=BT9-bACmLHDAqvEyr9zINw) instead of my directive, and use src attribute to include your "normal div" through a template. So assuming you put your div in `templates/to slide.html`, use this directive like so:

```html
<slick src="templates/to slide.html"></slick>
```
